export const buildSleepPremiumPrompt = (input, enforced) => {
  const answers = input.answers.map(({ questionId, question, answer }) => ({ questionId, question, answer }));
  const q6 = input.answers.find(({ questionId }) => questionId === "Q6");
  const examples = {
    "Osećaj po buđenju": "Probaj da pripremiš odeću i stvari za jutro još uveče; ujutru primeti koliko ti je lako da započneš dan.",
    "Period pre sna": q6?.mappedValue <= 2
      ? "Završi sadržaj koji gledaš pre odlaska u krevet i probaj deset minuta bez ekrana; primeti kako ti prija taj prelaz."
      : "Već imaš miran završetak večeri: probaj da obaveze za sutra ostaviš na papiru pre te rutine, umesto da dodaješ još pravila.",
    "Tok noći": "Pre spavanja namesti svetlo i posteljinu kako ti prija; ako se spontano probudiš, ujutru se priseti šta ti je tada smetalo.",
    "Vreme spavanja i buđenja": "Izaberi realan okvir za ustajanje prema svojim obavezama, bez skraćivanja vremena za san; primeti da li je izvodljiv.",
    "Više delova tvoje noći": "Prvo probaj jednostavniji završetak večeri, a drugi eksperiment neka bude priprema stvari za jutro; ne uvodi ih istog dana.",
    "Tvoj san u celini": "Zadrži ono što ti već prija i probaj mali večernji prelaz, poput pripreme stvari za sutra pre mirne rutine.",
  };
  return [
    "Pišeš koristan plaćeni Premium Result o snu na prirodnom, direktnom srpskom. Obraćaj se osobi sa ti, bez stručnog žargona i praznih fraza.",
    "Vrati samo JSON prema dostavljenoj strogoj šemi, version: 2. Zadrži tačno ključeve profile, profile_explanation, priority, connections, stable_or_tracking, seven_day_plan, alternatives, review_questions, after_seven_days, closing i supporting_content, uz version. Ne dodaj sekcije ili ključeve.",
    `Profil je konačan: „${enforced.profile}“. priority.title je tačno „TVOJ PRIORITET #1“, priority.area tačno „${enforced.priorityArea}“. Model nikada ne bira profil ili prioritet; ne menjaj ih i ne izvodi ocene.`,
    `stable_or_tracking.mode mora ostati „${enforced.mode}“ samo radi kompatibilnosti. Naslov je UVEK „ŠTA JOŠ VREDI DA PRATIŠ“, nezavisno od mode. Ne prikazuj režim ili interne podatke u tekstu.`,
    "Šest celina plaćene vrednosti: prioritet, povezivanje odgovora, dodatno praćenje, sedmodnevni plan, drugi pristup i isti sačuvani plan za budući PDF. profile_explanation je samo vrlo kratak uvodni tekst, ne glavna analiza.",
    `profile_explanation: jedna ili dve kratke rečenice, poželjno do 180 znakova, nikada više od ${enforced.profileExplanationMaxLength || 700}. Ukratko opiši sliku odgovora, bez ponavljanja naziva profila ili generičkog Free opisa.`,
    "priority.explanation: objasni zašto krenuti baš od fiksnog prioriteta, uz relevantne izabrane odgovore i jedan konkretan pravac za narednu nedelju. Razlikuj ono što osoba već radi od onoga što može tek da proba. Najviše 700 znakova.",
    "Svih 12 kanonskih pitanja i izabranih odgovora ispod koristi kao kontekst. Sažmi ih prirodno gde je korisno; nije potreban citat u svakoj rečenici. Ako koristiš navodnike „…“, prekopiraj ceo odgovarajući answer tačno, sa svim znakovima. Ne izmišljaj posao, porodicu, smene, obaveze, navike ili osećanja koji nisu navedeni.",
    "connections: 2–4 smislene veze ili kontrasta iz cele slike, ne samo ponavljanje dva odgovora. Svaki objekat ima tačno questionIds i text. questionIds sadrži tačno dva različita ID-ja iz ulaznih odgovora, kao podršku, ne kao prikaz korisniku. text do 500 znakova treba da poveže iskustva i kaže šta je praktično korisno uočiti. Uključi različite teme: jutro i dan, veče i misli, tok noći i ukupni utisak, trajanje i raspored. Kontrast navedi samo kada ga odgovori podržavaju; ne tvrdi da jedno objašnjava drugo. ID-jeve nikada ne piši u korisnički tekst.",
    "stable_or_tracking.items: 1–3 konkretne sporedne stvari koje osoba može da primeti naredne nedelje. Biraj ih iz preostalih odgovora: npr. razlika između dana sa alarmom i bez njega, lakoća ustajanja, misli pred san ili deo dana kada energija opada. To nisu novi prioriteti, lista problema, dijagnoze ili generičke pohvale.",
    "seven_day_plan: vrati TAČNO sedam objekata redom sa day vrednostima 1–7, svaki sa day, action i observe. action <=300 znakova, observe <=250; za mobilni prikaz ciljaj action <=150 i observe <=100. Kratak konkretan postupak i jedno jednostavno zapažanje, bez stalnog ponavljanja naziva prioriteta.",
    "Napredovanje plana: dan 1 početno zapažanje bez promene; dan 2 mali praktičan eksperiment; dan 3 prilagodi njegov obim ili trenutak; dan 4 uporedi sa početkom; dan 5 DRUGI, stvarno različit eksperiment, ne ista navika sa drugim trajanjem; dan 6 ponovi lakši praktičan postupak; dan 7 pregledaj iskustvo. Prvi eksperiment ostaje uz prioritet, drugi istražuje drugi praktičan pristup toj temi uz kontekst ostalih odgovora. Ne menjaj više stvari odjednom, ne svodi plan na pisanje beležaka.",
    `Jedan primer za trenutni prioritet, prilagodi ostalim odgovorima umesto da ga slepo prepišeš: ${examples[enforced.priorityArea] || examples["Tvoj san u celini"]}`,
    "Posebno poštuj odgovor o poslednjem delu večeri: ako već postoji mirna rutina bez ekrana, ne predstavljaj odlaganje telefona kao neophodan korak. Ako su misli aktivne uprkos mirnoj rutini, probaj završavanje planiranja pre nje. Ne pretpostavljaj telefon ako je izabran TV.",
    "alternatives: 1–2 konkretna, stvarno drugačija pristupa kada prvi postupak ne odgovara, pod naslovom prikaza „AKO TI PRVI KORAK NE ODGOVARA“. Naslov ne dodaj kao JSON ključ. Osloni se na druge odgovore, naročito večernju rutinu i misli. Ne nuditi samo praćenje, zapisivanje ili manju verziju istog eksperimenta; objasni šta osoba može da uradi umesto njega.",
    "review_questions: vrati TAČNO tri kratka, različita pitanja: šta je primećeno, koji postupak je izvodljiv i šta ima smisla probati sledeće. after_seven_days: objasni kako uporediti početak i kraj, šta zadržati i kada pokušati drugi pristup, bez obećanja ishoda.",
    "Ovaj JSON je jedini prihvaćeni izveštaj za web i budući PDF. Ne generiši zasebnu PDF verziju ili drugi izveštaj. PDF kasnije koristi iste sačuvane podatke; u korisničkom tekstu ne obećavaj da je PDF već dostupan.",
    "supporting_content je samo dopunsko objašnjenje ISTE analize, ne novi plan. answer_evidence: prekopiraj svih 12 originalnih {questionId, question, answer} redom i bez izmene. priority: context do 500 znakova dopunjuje postojeći razlog za prvi fokus; evidenceQuestionIds navodi 1–12 različitih originalnih ID-jeva. Ne dodaj drugi profil, prioritet ili medicinsko objašnjenje.",
    "supporting_content.connections: za svaku postojeću vezu tačno jedan {connectionIndex, context}, indeksi od nule redom; dopuni kontekst te iste veze bez nove interpretacije. tracking: tačno jedan {itemIndex, context} po postojećoj sporednoj stavci, indeksi od nule redom. alternatives: tačno jedan {alternativeIndex, context} po postojećem pristupu, indeksi od nule redom. Svi context tekstovi do 500 znakova, poželjno kraći; ne dodaj drugačije korake ili protivrečna tumačenja.",
    "supporting_content.days: tačno sedam {day, rationale, reflection} objekata redom. rationale do 250 znakova objašnjava praktičnost već navedene radnje, bez nove radnje ili obećanja. reflection je kratko pitanje do 200 znakova o istoj radnji i zapažanju ili null. Ne prepisuj i ne menjaj action ili observe. Za osvrt i završetak koristi postojeće review_questions, after_seven_days i closing, ne njihove nezavisne kopije. Sve zaštite od medicinskih, uzročnih i internih tvrdnji važe i za dopunski tekst.",
    "closing: kratka mirna informativna napomena. Ako teškoće dugo traju i znatno utiču na svakodnevicu, možeš predložiti razgovor sa zdravstvenim stručnjakom, bez alarmiranja.",
    "Zabranjeno u korisničkim tekstovima: dijagnoze, medicinske tvrdnje, lekovi, terapija, uzročna objašnjenja, obećanja boljeg sna, ocene, procenti i interni/tehnički termini. Praktična trajanja malih postupaka su dozvoljena. Ne tvrdi da nešto leči, rešava, reguliše, popravlja ili sigurno poboljšava san.",
    "Ne koristi robotske fraze „lični oslonac“, „smislen fokus za razmatranje“, „paralelno“ ili „bez donošenja zaključaka“. Piši jasno: šta odgovori pokazuju, šta konkretno probati i šta primetiti. Izbegni ponavljanje iste poruke u više celina.",
    `Fiksni podaci: ${JSON.stringify({ profile: enforced.profile, priorityArea: enforced.priorityArea, mode: enforced.mode, trackingTitle: "ŠTA JOŠ VREDI DA PRATIŠ" })}`,
    `Svih 12 kanonskih odgovora: ${JSON.stringify(answers)}`,
  ].join("\n");
};
