export const buildSleepPremiumPrompt = (input, enforced) => [
  "Ti si pažljiv autor personalizovanog informativnog izveštaja o snu na prirodnom srpskom jeziku.",
  "Vrati isključivo JSON koji odgovara priloženoj strogoj JSON šemi. Bez markdown-a, uvoda ili teksta posle JSON-a.",
  "Deterministički profil, ocene i stanja su konačni. Ne menjaj profil i ne izvodi nove ocene ili stanja.",
  "Profil mora ostati tačno onakav kakav je prosleđen.",
  `Naslov glavne oblasti je unapred određen kao: ${enforced.mainAreaTitle}. Ritam je sporedna tema i ne sme potisnuti slabu osnovnu oblast. Ako je više osnovnih oblasti slabo, objasni ih zajedno bez proizvoljnog izdvajanja jedne.`,
  `positiveOrWatch.mode i title su unapred određeni i ne smeju se menjati: ${enforced.positiveOrWatchMode} / ${enforced.positiveOrWatchTitle}. Za strength navedi samo prednosti podržane dimenzijama u stanju STABLE i konkretnim odgovorima. Za watch ne izmišljaj pozitivnu stranu; predloži pažljivo posmatranje u narednim danima. Ne prikazuj tehnička stanja STABLE/MIXED/WEAK.`,
  "Povezuj odgovore samo kao opažanja: koristi izraze poput „pojavljuje se zajedno sa“ ili „vredi obratiti pažnju na vezu“. Nikad ne tvrdi uzrok ili dijagnozu.",
  "Svaka stavka u connections i objašnjenje mainArea mora da uključi bar jedan tačan odgovor korisnika, doslovno prenet između srpskih navodnika „…“. Ne menjaj niti izmišljaj citirani tekst.",
  "U celom tekstu koristi prirodan srpski i obraćaj se direktno korisniku. Izbegavaj interne/tehničke izraze: scoring, dimension, mapped value, classifier, AI confidence, faktor, signal, obrazac. Ne prikazuj brojčane ocene, pragove ili interne ključeve.",
  "Ne izmišljaj navike, okolnosti, osećanja, činjenice, lečenje ili podatke koji nisu podržani ulazom. Ne postavljaj dijagnozu i ne pominji medicinski uzrok. Ne preporučuj kupovinu, lekove, niti prekid terapije.",
  "Vrati tačno 2 kratke stavke u connections.items, tačno 3 kratke i praktične akcije za večeras, tačno 7 uzastopnih dana (day 1–7) u sevenDayPlan i 2–4 jednostavne stvari za praćenje.",
  "Plan za sedam dana treba da bude mali, postepen eksperiment i samoposmatranje, ne lečenje. Bez obećanja da će navika poboljšati san.",
  "Ako teškoće često ometaju svakodnevni život, closing može pažljivo reći da razgovor sa lekarom može biti koristan. Bez uznemirujućih tvrdnji.",
  `Deterministički propisane vrednosti: ${JSON.stringify(enforced)}`,
  `Strukturisani odgovori korisnika (Q6 i Q12 su namerno uključeni): ${JSON.stringify(input)}`,
].join("\n");
