// Shared canonical sleep questionnaire copy used by the client and Premium report input.
export const SLEEP_QUESTIONS = Object.freeze([
  "Kada se probudiš ujutru, kako se najčešće osećaš?",
  "Legneš u krevet i ugasiš svetlo. Šta se obično desi?",
  "Šta se najčešće dešava tokom noći?",
  "Alarm zvoni. Kako izgleda tvoje ustajanje?",
  "Koliko sna obično imaš tokom jedne noći?",
  "Kako izgleda poslednjih 30 minuta pre spavanja?",
  "Kada legneš, koliko je tvoja glava „budna“?",
  "Kako izgleda tvoja energija tokom dana?",
  "Kada imaš slobodan dan i nema alarma, šta se događa?",
  "Koliko su ti vreme odlaska u krevet i vreme ustajanja predvidivi?",
  "Posle loše prospavane noći, šta najviše primetiš sledećeg dana?",
  "Kada razmisliš o svojim poslednjim noćima, koja rečenica ti je najbliža?",
]);

export const SLEEP_ANSWER_OPTIONS = Object.freeze([
  Object.freeze([
    { text: "Odmorno — spreman sam za dan", points: 5 },
    { text: "Uglavnom dobro, ali bih mogao još malo da spavam", points: 4 },
    { text: "Ni odmorno ni posebno umorno", points: 3 },
    { text: "Umorno — teško mi je da ustanem", points: 2 },
    { text: "Kao da nisam ni spavao", points: 1 },
  ]),
  Object.freeze([
    { text: "Zaspim vrlo brzo", points: 5 },
    { text: "Treba mi malo vremena", points: 4 },
    { text: "Često mi treba dosta vremena da zaspim", points: 3 },
    { text: "Misli mi ne daju da se isključim", points: 2 },
    { text: "Imam osećaj da se borim sa snom", points: 1 },
  ]),
  Object.freeze([
    { text: "Uglavnom spavam bez buđenja", points: 5 },
    { text: "Probudim se jednom i brzo nastavim da spavam", points: 4 },
    { text: "Budim se nekoliko puta", points: 3 },
    { text: "Kada se probudim, teško ponovo zaspim", points: 2 },
    { text: "Noć mi često deluje isprekidano", points: 1 },
  ]),
  Object.freeze([
    { text: "Ustanem bez problema", points: 5 },
    { text: "Treba mi nekoliko minuta", points: 4 },
    { text: "Odložim alarm jednom", points: 3 },
    { text: "Odlažem ga više puta", points: 2 },
    { text: "Jedva se nateram da ustanem", points: 1 },
  ]),
  Object.freeze([
    { text: "7–9 sati", points: 5 },
    { text: "6–7 sati", points: 4 },
    { text: "5–6 sati", points: 3 },
    { text: "Manje od 5 sati", points: 2 },
    { text: "Više od 9 sati, a ipak često nisam odmoran", points: 1 },
  ]),
  Object.freeze([
    { text: "Uglavnom se smirim bez ekrana", points: 5 },
    { text: "Imam svoju mirnu večernju rutinu", points: 4 },
    { text: "Gledam TV ili neki sadržaj", points: 3 },
    { text: "Telefon mi je često u ruci", points: 2 },
    { text: "Skrolujem dok ne postanem potpuno pospan", points: 1 },
  ]),
  Object.freeze([
    { text: "Lako se isključim", points: 5 },
    { text: "Razmišljam malo, pa se smirim", points: 4 },
    { text: "Vrtim događaje iz tog dana", points: 3 },
    { text: "Planiram, analiziram i razmišljam o problemima", points: 2 },
    { text: "Telo je umorno, ali mozak kao da ne želi da stane", points: 1 },
  ]),
  Object.freeze([
    { text: "Uglavnom je stabilna", points: 5 },
    { text: "Povremeno osetim umor", points: 4 },
    { text: "Često mi treba kafa ili pauza", points: 3 },
    { text: "Imam periode kada jedva držim oči otvorene", points: 2 },
    { text: "Veći deo dana osećam da mi nedostaje energije", points: 1 },
  ]),
  Object.freeze([
    { text: "Budim se približno u isto vreme", points: 5 },
    { text: "Spavam malo duže", points: 4 },
    { text: "Spavam znatno duže", points: 3 },
    { text: "Mogao bih da ostanem u krevetu pola dana", points: 2 },
    { text: "Vreme spavanja i buđenja mi se stalno menja", points: 1 },
  ]),
  Object.freeze([
    { text: "Skoro uvek su slični", points: 5 },
    { text: "Većinom imam isti ritam", points: 4 },
    { text: "Razlikuju se po nekoliko sati", points: 3 },
    { text: "Često nemam nikakav raspored", points: 2 },
    { text: "Svaki dan može izgledati potpuno drugačije", points: 1 },
  ]),
  Object.freeze([
    { text: "Malo toga — uglavnom funkcionišem normalno", points: 5 },
    { text: "Više sam umoran", points: 4 },
    { text: "Teže se koncentrišem", points: 3 },
    { text: "Umorniji sam i raspoloženje mi se promeni", points: 2 },
    { text: "Imam osećaj da samo pokušavam da preguram dan", points: 1 },
  ]),
  Object.freeze([
    { text: "Zadovoljan sam svojim snom", points: 5 },
    { text: "Uglavnom spavam dobro, uz poneku lošu noć", points: 4 },
    { text: "Moj san bi mogao biti bolji", points: 3 },
    { text: "Često imam osećaj da mi san nije dovoljan", points: 2 },
    { text: "Spavanje mi je postalo nešto sa čim se redovno borim", points: 1 },
  ]),
]);
